/**
 * The skill catalog: skills, prerequisites (graph edges) and the skills of each goal.
 * كتالوج المهارات: المهارات والاعتماديات (روابط الرسم) ومهارات كل هدف.
 *
 * A skill is stored once and can belong to many goals (for example Git or SQL),
 * so what a user learned stays saved when they change goal.
 */
import { GoalSkillTuple, SeedSkill } from './types';

export const SKILLS: SeedSkill[] = [
  // ---- Web ----
  { name: 'HTML', category: 'Frontend', hours: 10, description: 'Structure web pages with semantic HTML' },
  { name: 'CSS', category: 'Frontend', hours: 15, description: 'Style pages with selectors, the box model, Flexbox and Grid' },
  { name: 'Responsive Design', category: 'Frontend', hours: 10, description: 'Make layouts adapt to any screen size' },
  { name: 'JavaScript', category: 'Frontend', hours: 40, description: 'Core language of the web: functions, scope, async and the DOM' },
  { name: 'Git', category: 'Tools', hours: 8, description: 'Version control: commits, branches and collaboration' },
  { name: 'TypeScript', category: 'Frontend', hours: 20, description: 'Add static types to JavaScript' },
  { name: 'React', category: 'Frontend', hours: 35, description: 'Build user interfaces with components, state and hooks' },
  { name: 'State Management (Redux)', category: 'Frontend', hours: 15, description: 'Manage shared application state with Redux Toolkit' },
  { name: 'Web Accessibility', category: 'Frontend', hours: 10, description: 'Build interfaces everyone can use' },
  { name: 'Node.js', category: 'Backend', hours: 25, description: 'Run JavaScript on the server' },
  { name: 'Express', category: 'Backend', hours: 15, description: 'Build web servers and APIs with Express' },
  { name: 'SQL', category: 'Data', hours: 20, description: 'Query relational databases' },
  { name: 'PostgreSQL', category: 'Backend', hours: 15, description: 'Design and run a PostgreSQL database' },
  { name: 'REST APIs', category: 'Backend', hours: 12, description: 'Design resource-based HTTP APIs' },
  { name: 'Authentication (JWT)', category: 'Backend', hours: 12, description: 'Secure logins with hashed passwords and JWT' },
  // ---- Data ----
  { name: 'Excel', category: 'Data', hours: 15, description: 'Analyze data with spreadsheets, formulas and pivot tables' },
  { name: 'Python', category: 'Data', hours: 35, description: 'Programming fundamentals in Python' },
  { name: 'Statistics', category: 'Data', hours: 30, description: 'Descriptive statistics, probability and hypothesis testing' },
  { name: 'Pandas', category: 'Data', hours: 20, description: 'Analyze tabular data with pandas' },
  { name: 'Data Cleaning', category: 'Data', hours: 12, description: 'Fix missing values, duplicates and outliers' },
  { name: 'Data Visualization', category: 'Data', hours: 15, description: 'Choose and design charts that communicate clearly' },
  { name: 'Dashboards', category: 'Data', hours: 12, description: 'Build dashboards with KPIs for decision makers' },
  // ---- Security ----
  { name: 'Security Fundamentals', category: 'Security', hours: 15, description: 'CIA triad, threats, risk and basic controls' },
  { name: 'Networking Basics', category: 'Systems', hours: 20, description: 'IP, DNS, TCP/UDP and common protocols' },
  { name: 'Linux', category: 'Systems', hours: 25, description: 'Work with the Linux shell, files, permissions and processes' },
  { name: 'Cryptography', category: 'Security', hours: 20, description: 'Encryption, hashing and public-key cryptography' },
  { name: 'Web Security (OWASP)', category: 'Security', hours: 20, description: 'Common web vulnerabilities and how to prevent them' },
  { name: 'Network Security', category: 'Security', hours: 25, description: 'Firewalls, VPNs and intrusion detection' },
  { name: 'Vulnerability Assessment', category: 'Security', hours: 20, description: 'Find, score and report weaknesses' },
  { name: 'Incident Response', category: 'Security', hours: 15, description: 'Detect, contain and recover from security incidents' },
  // ---- Design ----
  { name: 'Design Principles', category: 'Design', hours: 12, description: 'Hierarchy, consistency and usability heuristics' },
  { name: 'Color & Typography', category: 'Design', hours: 10, description: 'Use color and type for readable, attractive interfaces' },
  { name: 'User Research', category: 'Design', hours: 15, description: 'Learn about users with interviews, surveys and observation' },
  { name: 'Wireframing', category: 'Design', hours: 10, description: 'Sketch screen structure and user flows' },
  { name: 'Figma', category: 'Design', hours: 20, description: 'Design interfaces with frames, components and auto layout' },
  { name: 'Prototyping', category: 'Design', hours: 15, description: 'Create interactive prototypes' },
  { name: 'Usability Testing', category: 'Design', hours: 12, description: 'Test designs with real users' },
  { name: 'Design Systems', category: 'Design', hours: 20, description: 'Build reusable components, tokens and guidelines' },
  // ---- DevOps ----
  { name: 'Bash Scripting', category: 'DevOps', hours: 15, description: 'Automate tasks with shell scripts' },
  { name: 'Docker', category: 'DevOps', hours: 20, description: 'Package apps into containers' },
  { name: 'CI/CD', category: 'DevOps', hours: 18, description: 'Automate builds, tests and deployments' },
  { name: 'Cloud Basics', category: 'DevOps', hours: 20, description: 'Cloud service models, compute, storage and cost' },
  { name: 'Kubernetes', category: 'DevOps', hours: 30, description: 'Orchestrate containers at scale' },
  { name: 'Monitoring', category: 'DevOps', hours: 12, description: 'Metrics, logs, alerts and reliability targets' },
];

/** [skill, prerequisite]: the skill unlocks only after its prerequisite is mastered */
export const DEPENDENCIES: [skill: string, prerequisite: string][] = [
  ['CSS', 'HTML'],
  ['Responsive Design', 'CSS'],
  ['JavaScript', 'HTML'],
  ['TypeScript', 'JavaScript'],
  ['React', 'JavaScript'],
  ['State Management (Redux)', 'React'],
  ['Web Accessibility', 'HTML'],
  ['Node.js', 'JavaScript'],
  ['Express', 'Node.js'],
  ['PostgreSQL', 'SQL'],
  ['REST APIs', 'Express'],
  ['Authentication (JWT)', 'REST APIs'],

  ['Pandas', 'Python'],
  ['Data Cleaning', 'Pandas'],
  ['Data Visualization', 'Pandas'],
  ['Data Visualization', 'Statistics'],
  ['Dashboards', 'Data Visualization'],
  ['Dashboards', 'SQL'],

  ['Cryptography', 'Security Fundamentals'],
  ['Web Security (OWASP)', 'Security Fundamentals'],
  ['Network Security', 'Security Fundamentals'],
  ['Network Security', 'Networking Basics'],
  ['Vulnerability Assessment', 'Network Security'],
  ['Vulnerability Assessment', 'Linux'],
  ['Incident Response', 'Vulnerability Assessment'],

  ['Color & Typography', 'Design Principles'],
  ['Wireframing', 'Design Principles'],
  ['Wireframing', 'User Research'],
  ['Figma', 'Wireframing'],
  ['Prototyping', 'Figma'],
  ['Usability Testing', 'User Research'],
  ['Usability Testing', 'Prototyping'],
  ['Design Systems', 'Color & Typography'],
  ['Design Systems', 'Prototyping'],

  ['Bash Scripting', 'Linux'],
  ['Docker', 'Linux'],
  ['CI/CD', 'Git'],
  ['CI/CD', 'Docker'],
  ['Cloud Basics', 'Networking Basics'],
  ['Cloud Basics', 'Linux'],
  ['Kubernetes', 'Docker'],
  ['Kubernetes', 'Cloud Basics'],
  ['Monitoring', 'Docker'],
];

/** The seven goals. Names must match the goals created by seedData.ts */
export const GOAL_SKILLS: Record<string, GoalSkillTuple[]> = {
  'Full Stack Developer': [
    ['HTML', 0.7, 0.7],
    ['CSS', 0.7, 0.7],
    ['JavaScript', 0.75, 1.0],
    ['Git', 0.7, 0.6],
    ['TypeScript', 0.7, 0.7],
    ['React', 0.75, 0.95],
    ['Node.js', 0.75, 0.9],
    ['Express', 0.7, 0.85],
    ['SQL', 0.7, 0.8],
    ['REST APIs', 0.7, 0.85],
  ],
  'Frontend Developer': [
    ['HTML', 0.75, 0.8],
    ['CSS', 0.75, 0.85],
    ['Responsive Design', 0.7, 0.8],
    ['JavaScript', 0.8, 1.0],
    ['Git', 0.7, 0.5],
    ['TypeScript', 0.75, 0.75],
    ['React', 0.8, 1.0],
    ['State Management (Redux)', 0.7, 0.7],
    ['Web Accessibility', 0.7, 0.6],
  ],
  'Backend Developer': [
    ['JavaScript', 0.75, 0.8],
    ['Git', 0.7, 0.6],
    ['TypeScript', 0.7, 0.7],
    ['Node.js', 0.8, 1.0],
    ['Express', 0.75, 0.9],
    ['SQL', 0.8, 0.9],
    ['PostgreSQL', 0.75, 0.9],
    ['REST APIs', 0.75, 0.9],
    ['Authentication (JWT)', 0.7, 0.8],
  ],
  'Data Analyst': [
    ['Excel', 0.7, 0.6],
    ['SQL', 0.8, 1.0],
    ['Python', 0.75, 0.95],
    ['Statistics', 0.75, 0.9],
    ['Pandas', 0.75, 0.9],
    ['Data Cleaning', 0.7, 0.8],
    ['Data Visualization', 0.7, 0.8],
    ['Dashboards', 0.7, 0.7],
  ],
  'Cybersecurity Specialist': [
    ['Security Fundamentals', 0.75, 0.9],
    ['Networking Basics', 0.75, 0.85],
    ['Linux', 0.75, 0.8],
    ['Cryptography', 0.7, 0.8],
    ['Web Security (OWASP)', 0.75, 0.9],
    ['Network Security', 0.75, 0.9],
    ['Vulnerability Assessment', 0.7, 0.85],
    ['Incident Response', 0.7, 0.8],
  ],
  'UI/UX Designer': [
    ['Design Principles', 0.75, 0.9],
    ['Color & Typography', 0.7, 0.7],
    ['User Research', 0.75, 0.9],
    ['Wireframing', 0.7, 0.8],
    ['Figma', 0.75, 0.85],
    ['Prototyping', 0.7, 0.8],
    ['Usability Testing', 0.7, 0.8],
    ['Design Systems', 0.65, 0.7],
  ],
  'DevOps Engineer': [
    ['Linux', 0.75, 0.9],
    ['Git', 0.75, 0.7],
    ['Networking Basics', 0.7, 0.7],
    ['Bash Scripting', 0.7, 0.8],
    ['Docker', 0.75, 1.0],
    ['CI/CD', 0.75, 0.9],
    ['Cloud Basics', 0.7, 0.85],
    ['Kubernetes', 0.7, 0.8],
    ['Monitoring', 0.7, 0.7],
  ],
};